In [ ]:
# Импортируем объект Counter из модуля collections
from collections import Counter
# Создаём пустой объект Counter
c = Counter()

In [ ]:
c['red'] += 1
print(c)
# Будет напечатано:
# Counter({'red': 1})

Counter({'red': 1})


In [ ]:
cars = ['red', 'blue', 'black', 'black', 'black', 'red', 'blue', 'red', 'white']

In [ ]:
c = Counter()
for car in cars:
    c[car] += 1
 
print(c)
# Counter({'red': 3, 'black': 3, 'blue': 2, 'white': 1})

Counter({'red': 3, 'black': 3, 'blue': 2, 'white': 1})


In [ ]:
c = Counter(cars)
print(c)
# Counter({'red': 3, 'black': 3, 'blue': 2, 'white': 1})

Counter({'red': 3, 'black': 3, 'blue': 2, 'white': 1})


In [ ]:
print(c['black'])
# 3

3


In [ ]:
print(c['purple'])
# 0

0


In [ ]:
print(sum(c.values()))
# 9

9


In [ ]:
print(c.values())
# dict_values([3, 2, 3, 1])

dict_values([3, 2, 3, 1])


In [ ]:
cars_moscow = ['black', 'black', 'white', 'black', 'black', 'white', 'yellow', 'yellow', 'yellow']
cars_spb = ['red', 'black', 'black', 'white', 'white', 'yellow', 'yellow', 'red', 'white']

In [ ]:
counter_moscow = Counter(cars_moscow)
counter_spb = Counter(cars_spb)
 
print(counter_moscow)
print(counter_spb)
 
# Counter({'black': 4, 'yellow': 3, 'white': 2})
# Counter({'white': 3, 'red': 2, 'black': 2, 'yellow': 2})

Counter({'black': 4, 'yellow': 3, 'white': 2})
Counter({'white': 3, 'red': 2, 'black': 2, 'yellow': 2})


In [ ]:
print(counter_moscow + counter_spb)
# Counter({'black': 6, 'white': 5, 'yellow': 5, 'red': 2})

Counter({'black': 6, 'white': 5, 'yellow': 5, 'red': 2})


In [ ]:
print(counter_moscow)
print(counter_spb)
# Counter({'black': 4, 'yellow': 3, 'white': 2})
# Counter({'white': 3, 'red': 2, 'black': 2, 'yellow': 2})
 
counter_moscow.subtract(counter_spb)
print(counter_moscow)
# Counter({'black': 2, 'yellow': 1, 'white': -1, 'red': -2})

Counter({'black': 4, 'yellow': 3, 'white': 2})
Counter({'white': 3, 'red': 2, 'black': 2, 'yellow': 2})
Counter({'black': 2, 'yellow': 1, 'white': -1, 'red': -2})


In [ ]:
# Пересоздаём счётчики, потому что объект counter_moscow поменял свои значения
# после функции subtract.
counter_moscow = Counter(cars_moscow)
counter_spb = Counter(cars_spb)
 
print(counter_moscow - counter_spb)
# Counter({'black': 2, 'yellow': 1})

Counter({'black': 2, 'yellow': 1})


In [ ]:
print(*counter_moscow.elements())
# black black black black white white yellow yellow yellow

black black black black white white yellow yellow yellow


In [ ]:
print(list(counter_moscow))
# ['black', 'white', 'yellow']

['black', 'white', 'yellow']


In [ ]:
print(dict(counter_moscow))
# {'black': 4, 'white': 2, 'yellow': 3}

{'black': 4, 'white': 2, 'yellow': 3}


In [ ]:
print(counter_moscow.most_common())
# [('black', 4), ('yellow', 3), ('white', 2)]

[('black', 4), ('yellow', 3), ('white', 2)]


In [ ]:
print(counter_moscow.most_common(2))
# [('black', 4), ('yellow', 3)]

[('black', 4), ('yellow', 3)]


In [ ]:
counter_moscow.clear()
print(counter_moscow)
# Counter()

Counter()


In [ ]:
# Задание 2.3
# Задание 2.4
# Задание 2.5
# from hidden import clients
# from collections import Counter
# # Пишите здесь команды, которые помогут
# # найти ответы на вопросы
# counter_clients = Counter(clients)
# # print(list(counter_clients))
# # print(dict(counter_clients))
# # print(counter_clients.most_common(1))
# # print(counter_clients[953421102])
# print(len(set(counter_clients.keys())))



---

DEFAULTDICT

In [ ]:
students = [('Ivanov',1),('Smirnov',4),('Petrov',3),('Kuznetsova',1),
            ('Nikitina',2),('Markov',3),('Pavlov',2)]

In [ ]:
groups = dict()
 
for student, group in students:
    # Проверяем, есть ли уже эта группа в словаре
    if group not in groups:
        # Если группы ещё нет в словаре, создаём для неё пустой список
        groups[group] = list()
    groups[group].append(student)
 
print(groups)
# {1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov', 'Markov'], 2: ['Nikitina', 'Pavlov']}

{1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov', 'Markov'], 2: ['Nikitina', 'Pavlov']}




---


In [ ]:
from collections import defaultdict
groups = defaultdict(list)

In [ ]:
for student, group in students:
    groups[group].append(student)
 
print(groups)
# defaultdict(<class 'list'>, {1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov', 'Markov'], 2: ['Nikitina', 'Pavlov']})

defaultdict(<class 'list'>, {1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov', 'Markov'], 2: ['Nikitina', 'Pavlov']})


In [ ]:
print(groups[3])
# ['Petrov', 'Markov']

['Petrov', 'Markov']


In [ ]:
print(groups[2021])
# []

[]


In [ ]:
print(groups)
# defaultdict(<class 'list'>, {1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov', 'Markov'], 2: ['Nikitina', 'Pavlov'], 2021: []})

defaultdict(<class 'list'>, {1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov', 'Markov'], 2: ['Nikitina', 'Pavlov'], 2021: []})


In [ ]:
dict_object = dict()
defaultdict_object = defaultdict()
 
print(type(dict_object))
# <class 'dict'>
print(type(defaultdict_object))
# <class 'collections.defaultdict'>

<class 'dict'>
<class 'collections.defaultdict'>


In [ ]:
print(dict_object)
# {}
print(defaultdict_object)
# defaultdict(None, {})

{}
defaultdict(None, {})




---

# 3. Модуль Collections. Deque и OrderedDict

ORDEREDDICT

In [ ]:
# Напоминаем способ создания словаря через список кортежей
# (ключ, значение)
data = [('Ivan', 19),('Mark', 25),('Andrey', 23),('Maria', 20)]
client_ages = dict(data)
print(client_ages)
# По результатам 3 повторов получились вот такие результаты:
# {'Maria': 20, 'Mark': 25, 'Ivan': 19, 'Andrey': 23}
# {'Ivan': 19, 'Andrey': 23, 'Mark': 25, 'Maria': 20}
# {'Andrey': 23, 'Mark': 25, 'Maria': 20, 'Ivan': 19}

{'Ivan': 19, 'Mark': 25, 'Andrey': 23, 'Maria': 20}


In [ ]:
from collections import OrderedDict
data = [('Ivan', 19),('Mark', 25),('Andrey', 23),('Maria', 20)]
ordered_client_ages = OrderedDict(data)
print(ordered_client_ages)
# По результатам 3 повторов получились вот такие результаты:
# OrderedDict([('Ivan', 19), ('Mark', 25), ('Andrey', 23), ('Maria', 20)])
# OrderedDict([('Ivan', 19), ('Mark', 25), ('Andrey', 23), ('Maria', 20)])
# OrderedDict([('Ivan', 19), ('Mark', 25), ('Andrey', 23), ('Maria', 20)])

OrderedDict([('Ivan', 19), ('Mark', 25), ('Andrey', 23), ('Maria', 20)])


In [ ]:
data = [('Ivan', 19),('Mark', 25),('Andrey', 23),('Maria', 20)]
# Сортируем по второму значению из кортежа, то есть по возрасту
ordered_client_ages = OrderedDict(sorted(data, key=lambda x: x[1]))
print(ordered_client_ages)
# OrderedDict([('Ivan', 19), ('Maria', 20), ('Andrey', 23), ('Mark', 25)])

OrderedDict([('Ivan', 19), ('Maria', 20), ('Andrey', 23), ('Mark', 25)])


In [ ]:
ordered_client_ages['Nikita'] = 18
print(ordered_client_ages)
# OrderedDict([('Ivan', 19), ('Maria', 20), ('Andrey', 23), ('Mark', 25), ('Nikita', 18)])

OrderedDict([('Ivan', 19), ('Maria', 20), ('Andrey', 23), ('Mark', 25), ('Nikita', 18)])


In [ ]:
del ordered_client_ages['Andrey']
print(ordered_client_ages)
# OrderedDict([('Ivan', 19), ('Mark', 25), ('Maria', 20), ('Nikita', 18)])
ordered_client_ages['Andrey'] = 23
print(ordered_client_ages)
# OrderedDict([('Ivan', 19), ('Mark', 25), ('Maria', 20), ('Nikita', 18), ('Andrey', 23)])

OrderedDict([('Ivan', 19), ('Maria', 20), ('Mark', 25), ('Nikita', 18)])
OrderedDict([('Ivan', 19), ('Maria', 20), ('Mark', 25), ('Nikita', 18), ('Andrey', 23)])


In [ ]:
import sys
print(sys.version)
# 3.4.3 (default, Nov 12 2018, 22:25:49)
# [GCC 4.8.4]

3.7.15 (default, Oct 12 2022, 19:14:55) 
[GCC 7.5.0]




---

DEQUE

In [ ]:
from collections import deque
dq = deque()
print(dq)
# deque([])

deque([])


In [ ]:
clients = deque()
clients.append('Ivanov')
clients.append('Petrov')
clients.append('Smirnov')
clients.append('Tikhonova')
print(clients)
# deque(['Ivanov', 'Petrov', 'Smirnov', 'Tikhonova'])

deque(['Ivanov', 'Petrov', 'Smirnov', 'Tikhonova'])


In [ ]:
print(clients[2])
# Smirnov

Smirnov


In [ ]:
first_client = clients.popleft()
second_client = clients.popleft()
 
print("First client:", first_client)
print("Second client:", second_client)
print(clients)
# First client: Ivanov
# Second client: Petrov
# deque(['Smirnov', 'Tikhonova'])

First client: Ivanov
Second client: Petrov
deque(['Smirnov', 'Tikhonova'])


In [ ]:
clients.appendleft('Vip-client')
 
print(clients)
# deque(['Vip-client', 'Smirnov', 'Tikhonova'])

deque(['Vip-client', 'Smirnov', 'Tikhonova'])


In [ ]:
tired_client = clients.pop()
print(tired_client, "left the queue")
print(clients)
# Tikhonova left the queue
# deque(['Vip-client', 'Smirnov'])

Tikhonova left the queue
deque(['Vip-client', 'Smirnov'])


In [ ]:
clients = deque(['Ivanov', 'Petrov', 'Smirnov', 'Tikhonova'])
print(clients)
# deque(['Ivanov', 'Petrov', 'Smirnov', 'Tikhonova'])
del clients[2]
print(clients)
# deque(['Ivanov', 'Petrov', 'Tikhonova'])

deque(['Ivanov', 'Petrov', 'Smirnov', 'Tikhonova'])
deque(['Ivanov', 'Petrov', 'Tikhonova'])


In [ ]:
# В скобках передаём список при создании deque,
# чтобы сразу добавить все его элементы в очередь
shop = deque([1, 2, 3, 4, 5])
print(shop)
# deque([1, 2, 3, 4, 5])
shop.extend([11, 12, 13, 14, 15, 16, 17])
print(shop)
# deque([1, 2, 3, 4, 5, 11, 12, 13, 14, 15, 16, 17])

deque([1, 2, 3, 4, 5])
deque([1, 2, 3, 4, 5, 11, 12, 13, 14, 15, 16, 17])


In [ ]:
shop = deque([1, 2, 3, 4, 5])
print(shop)
# deque([1, 2, 3, 4, 5])
shop.extendleft([11, 12, 13, 14, 15, 16, 17])
print(shop)
# deque([17, 16, 15, 14, 13, 12, 11, 1, 2, 3, 4, 5])

deque([1, 2, 3, 4, 5])
deque([17, 16, 15, 14, 13, 12, 11, 1, 2, 3, 4, 5])




---

ОЧЕРЕДЬ С ОГРАНИЧЕННОЙ МАКСИМАЛЬНОЙ ДЛИНОЙ

In [ ]:
limited = deque(maxlen=3)
print(limited)
# deque([], maxlen=3)
 
limited_from_list = deque([1,3,4,5,6,7], maxlen=3)
print(limited_from_list)
# deque([5, 6, 7], maxlen=3)

deque([], maxlen=3)
deque([5, 6, 7], maxlen=3)


In [ ]:
limited.extend([1,2,3])
print(limited)
# deque([1, 2, 3], maxlen=3)
 
print(limited.append(8))
# None
print(limited)
# deque([2, 3, 8], maxlen=3)

deque([1, 2, 3], maxlen=3)
None
deque([2, 3, 8], maxlen=3)


In [ ]:
temps = [20.6, 19.4, 19.0, 19.0, 22.1,
        22.5, 22.8, 24.1, 25.6, 27.0,
        27.0, 25.6, 26.8, 27.3, 22.5,
        25.4, 24.4, 23.7, 23.6, 22.6,
        20.4, 17.9, 17.3, 17.3, 18.1,
        20.1, 22.2, 19.8, 21.3, 21.3,
        21.9]

In [ ]:
days = deque(maxlen=7)
 
for temp in temps:
    # Добавляем температуру в очередь
    days.append(temp)
    # Если длина очереди оказалась равной максимальной длине очереди (7),
    # печатаем среднюю температуру за последние 7 дней
    if len(days) == days.maxlen:
        print(round(sum(days) / len(days), 2), end='; ')
# Напечатаем пустую строку, чтобы завершить действие параметра
# end. Иначе следующая строка окажется напечатанной на предыдущей
print("")
# Результат:
# 20.77; 21.27; 22.16; 23.3; 24.44; 24.94; 25.56; 26.2; 25.97;
# 25.94; 25.57; 25.1; 24.81; 24.21; 23.23; 22.57; 21.41; 20.4;
# 19.6; 19.1; 19.04; 18.96; 19.44; 20.01; 20.67;

20.77; 21.27; 22.16; 23.3; 24.44; 24.94; 25.56; 26.2; 25.97; 25.94; 25.57; 25.1; 24.81; 24.21; 23.23; 22.57; 21.41; 20.4; 19.6; 19.1; 19.04; 18.96; 19.44; 20.01; 20.67; 




---

ДОПОЛНИТЕЛЬНЫЕ ФУНКЦИИ

In [ ]:
dq = deque([1,2,3,4,5])
print(dq)
# deque([1, 2, 3, 4, 5])
 
dq.reverse()
print(dq)
# deque([5, 4, 3, 2, 1])

deque([1, 2, 3, 4, 5])
deque([5, 4, 3, 2, 1])


In [ ]:
dq = deque([1,2,3,4,5])
print(dq)
# deque([1, 2, 3, 4, 5])
 
dq.rotate(2)
print(dq)
# deque([4, 5, 1, 2, 3])

deque([1, 2, 3, 4, 5])
deque([4, 5, 1, 2, 3])


In [ ]:
dq = deque([1,2,3,4,5])
print(dq)
# deque([1, 2, 3, 4, 5])
 
# Отрицательное значение аргумента переносит
# n элементов из начала в конец
dq.rotate(-2)
print(dq)
# deque([3, 4, 5, 1, 2])

deque([1, 2, 3, 4, 5])
deque([3, 4, 5, 1, 2])


In [ ]:
dq = [1,2,4,2,3,1,5,4,4,4,4,4,3]
print(dq.index(4))
# 2
print(dq.count(4))
# 6

2
6


In [ ]:
dq = deque([1,2,4,2,3,1,5,4,4,4,4,4,3])
print(dq.index(25))
# ValueError: 25 is not in deque

In [ ]:
dq = deque([1,2,4,2,3,1,5,4,4,4,4,4,3])
print(dq.count(25))
# 0

0


In [ ]:
dq = deque([1,2,4,2,3,1,5,4,4,4,4,4,3])
print(dq)
# deque([1, 2, 4, 2, 3, 1, 5, 4, 4, 4, 4, 4, 3])
dq.clear()
print(dq)
# deque([])

deque([1, 2, 4, 2, 3, 1, 5, 4, 4, 4, 4, 4, 3])
deque([])




---



In [ ]:
# Задание 3.2
# Дан список из кортежей temps. 
# На первом месте в кортеже указан год в виде строки, 
# а на втором — средняя температура января в Петербурге в указанном году.
# Необходимо напечатать словарь, в котором ключи — годы, 
# а значения — показатели температуры. 
# Ключи необходимо отсортировать в порядке убывания соответствующих им температур.

temps = [('2000', -4.4), ('2001', -2.5), ('2002', -4.4), ('2003', -9.5),
        ('2004', -8.2), ('2005', -1.6), ('2006', -5.9), ('2007', -2.4),
        ('2008', -1.7), ('2009', -3.5), ('2010', -12.1), ('2011', -5.8),
        ('2012', -4.9), ('2013', -6.1), ('2014', -6.9), ('2015', -2.7),
        ('2016', -11.2), ('2017', -3.9), ('2018', -2.9), ('2019', -6.5),
        ('2020', 1.5)]
         
# Напечатайте словарь из температур, отсортированный по уменьшению температуры
from collections import OrderedDict

ordered_temps = OrderedDict(sorted(temps, key=lambda x: x[1], reverse=True))
print(ordered_temps)

OrderedDict([('2020', 1.5), ('2005', -1.6), ('2008', -1.7), ('2007', -2.4), ('2001', -2.5), ('2015', -2.7), ('2018', -2.9), ('2009', -3.5), ('2017', -3.9), ('2000', -4.4), ('2002', -4.4), ('2012', -4.9), ('2011', -5.8), ('2006', -5.9), ('2013', -6.1), ('2019', -6.5), ('2014', -6.9), ('2004', -8.2), ('2003', -9.5), ('2016', -11.2), ('2010', -12.1)])


In [ ]:
# Задание 3.5
# Извлеките элемент из начала очереди. 
# Запишите полученное значение элемента в качестве ответа.

# Задание 3.6
# В уже модифицированной очереди переместите пять элементов из начала очереди в её конец. 
# Извлеките последний элемент из очереди. Запишите полученное число в качестве ответа.

# Задание 3.7
# Сколько задач с тем номером, что был извлечён в предыдущем задании, 
# осталось в модифицированной очереди? Запишите ответ в числовой форме.

# from hidden import users

# # Пишите здесь команды, который помогут
# # найти ответы на вопросы

# from collections import Counter
# # from collections import defaultdict
# from collections import deque
# # from collections import OrderedDict

# clients = deque(users)
# print(clients)
# first_client = clients.popleft()
# print(first_client)

# clients.rotate(-5)
# last_clients = clients.pop()
# print(last_clients)

# print(clients)
# print(clients.count(8))



---

# 4. Модуль Collections. Закрепление знаний

In [ ]:
# ЗАДАНИЕ 4.3
# Напишите функцию brackets(line), которая определяет, 
# является ли последовательность из круглых скобок правильной.
# Правильной скобочной последовательностью назовём такую последовательность скобок, 
# в которой для каждой открывающей скобки есть последующая соответствующая ей закрывающая скобка.
# Соответственно, остальные скобочные последовательности назовём неправильными.
# Пустую строку будем считать правильной последовательностью.
# Для решения этой задачи потребуется использовать стек.
# Посимвольно переберите строку. 
# Если встретилась открывающаяся скобка, положите её в стек. 
# Если встретилась закрывающаяся скобка, извлеките скобку из стека.
# Если стек пустой, то есть извлечь скобку нельзя, последовательность неправильная.
# Если строка закончилась и стек стал пустым, последовательность правильная.
# Если в стеке остались скобки, последовательность неправильная.

from collections import deque

def brackets(line):
    # Напишите тело функции
    queue = deque()
    for symb in line:
        if symb == ')':
            if queue:
               queue.pop()
               continue
            return False
        elif symb == '(':
            queue.append(symb)
    return not bool(queue)

In [ ]:
print(brackets("(()())"))
# True
print(brackets(""))
# True
print(brackets("(()()))"))
# False

True
True
False




---



In [ ]:
# from hidden import north, center, south
# # Пишите здесь команды, которые помогут
# # найти ответы на вопросы
# # print(north)
# # print(center)
# # print(south)

# from collections import Counter

# def flatten(l):
#     return [item for sublist in l for item in sublist]

# # print(len(flatten(north)))
# # print(len(flatten(center)))
# # print(len(flatten(south)))
# # print(flatten(north))

# c_north = Counter(flatten(north))
# c_center = Counter(flatten(center))
# c_south = Counter(flatten(south))

# print(c_north)
# print(c_center)
# print(c_south)

# print(c_north + c_center + c_south)

# # from collections import OrderedDict
# # ordered_c_north = sorted(c_north, key=lambda x: x[1])
# # print(ordered_c_north)



---



In [ ]:
# ЗАДАНИЕ 4.9
# Дан список кортежей ratings с рейтингами кафе. 
# Кортеж состоит из названия и рейтинга кафе.
# Необходимо отсортировать список кортежей по убыванию рейтинга. 
# Если рейтинги совпадают, 
# то отсортировать кафе дополнительно по названию в алфавитном порядке.
# Получите словарь cafes с упорядоченными ключами из отсортированного списка, 
# где ключи — названия кафе, а значения — их рейтинг.
ratings = [('Old York', 3.3), ('New Age', 4.6), ('Old Gold', 3.3), ('General Foods', 4.8),
           ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1),
           ('WokToWork', 4.9), ('WokAndRice', 4.9), ('Old Wine Cellar', 3.3), ('Nice Cakes', 3.9)]

# Отсортируйте список ratings по убыванию рейтинга. Для кафе
# с одинаковым рейтингом отсортируйте кортежи по названию.


# Сохраните данные с рейтингом в словарь cafes, где ключами являются
# названия кафе, а значениями - их рейтинг.
from collections import OrderedDict
cafes = OrderedDict(sorted(ratings, key=lambda x: (-x[1], x[0])))
print(cafes)

OrderedDict([('WokAndRice', 4.9), ('WokToWork', 4.9), ('General Foods', 4.8), ('New Age', 4.6), ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1), ('Nice Cakes', 3.9), ('Old Gold', 3.3), ('Old Wine Cellar', 3.3), ('Old York', 3.3)])




---



In [ ]:
# ЗАДАНИЕ 4.10
# Напишите функцию task_manager, которая принимает список задач для нескольких серверов. 
# Каждый элемент списка состоит из кортежа 
# (<номер задачи>, <название сервера>, <высокий приоритет задачи>).

# Функция должна создавать словарь и заполнять его задачами по следующему принципу: 
# название сервера — ключ, по которому хранится очередь задач для конкретного сервера. 
# Если поступает задача без высокого приоритета (последний элемент кортежа — False), 
# добавить номер задачи в конец очереди. Если приоритет высокий, добавить номер в начало.

# Для словаря используйте defaultdict, для очереди — deque.

# Функция возвращает полученный словарь с задачами.

tasks1 = [(36871, 'office', False),
(40690, 'office', False),
(35364, 'voltage', False),
(41667, 'voltage', True),
(33850, 'office', False)]

from collections import defaultdict
from collections import deque

def task_manager(tasks):
    servers = defaultdict(deque)
    for task, server, priority in tasks:
        if priority:
            servers[server].appendleft(task)
        else:
            servers[server].append(task)
        
    return servers


print(task_manager(tasks1))

defaultdict(<class 'collections.deque'>, {'office': deque([36871, 40690, 33850]), 'voltage': deque([41667, 35364])})




---

# 5. Модуль NumPy. Типы данных

In [ ]:
-(2**16)/2

-32768.0

In [ ]:
(2**16)/2 - 1

32767.0

In [ ]:
import numpy as np
a = np.int8(25)
print(a)
# 25

25


In [ ]:
print(type(a))
# <class 'numpy.int8'>

<class 'numpy.int8'>


In [ ]:
# Можно применить к самому
# названию типа данных
np.iinfo(np.int8)
# iinfo(min=-128, max=127, dtype=int8)

iinfo(min=-128, max=127, dtype=int8)

In [ ]:
# Можно применить к существующему
# конкретному объекту
np.iinfo(a)
# iinfo(min=-128, max=127, dtype=int8)

iinfo(min=-128, max=127, dtype=int8)

In [ ]:
np.iinfo(np.int16)

iinfo(min=-32768, max=32767, dtype=int16)

In [ ]:
np.iinfo(np.int32)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [ ]:
np.iinfo(np.int64)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)



---



In [ ]:
b = np.uint8(124)
print(b)
# 124
print(type(b))
# <class 'numpy.uint8'>
np.iinfo(b)
# iinfo(min=0, max=255, dtype=uint8)

124
<class 'numpy.uint8'>


iinfo(min=0, max=255, dtype=uint8)

In [ ]:
c = np.int8(124)
print(c)
print(type(c))
np.iinfo(c)

124
<class 'numpy.int8'>


iinfo(min=-128, max=127, dtype=int8)

In [ ]:
a = np.int32(1000)
print(a)
# 1000
print(type(a))
# <class 'numpy.int32'>
a = 2056
print(a)
# 2056
print(type(a))
# <class 'int'>

1000
<class 'numpy.int32'>
2056
<class 'int'>


In [ ]:
a = np.int32(1000)
print(a)
# 1000
print(type(a))
# <class 'numpy.int32'>
a = np.int32(2056)
print(a)
# 2056
print(type(a))
# <class 'numpy.int32'>

1000
<class 'numpy.int32'>
2056
<class 'numpy.int32'>


In [ ]:
a = np.int32(1000)
b = a + 25
print(b)
# 1025
print(type(b))
# <class 'numpy.int64'>

1025
<class 'numpy.int64'>


In [ ]:
a = np.int32(1000)
b = np.int8(25)
c = a + b
print(c)
# 1025
print(type(c))
# <class 'numpy.int32'>

1025
<class 'numpy.int32'>


In [ ]:
a = np.int8(260)
print(a)
# 4

4


In [ ]:
a = np.int32(2147483610)
b = np.int32(2147483605)
print(a, b)
# 2147483610 2147483605
print(a + b)
# -81
# RuntimeWarning: overflow encountered in int_scalars
# Переполнено int'овое значение

2147483610 2147483605
-81


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: overflow encountered in int_scalars
  """


In [ ]:
a = np.int32(2147483610)
b = np.int32(2147483605)
print(a, b)
# 2147483610 2147483605
print(np.int64(a) + np.int64(b))
# 4294967215

2147483610 2147483605
4294967215


In [ ]:
np.finfo(np.float16)
# finfo(resolution=0.001, min=-6.55040e+04, max=6.55040e+04, dtype=float16)

finfo(resolution=0.001, min=-6.55040e+04, max=6.55040e+04, dtype=float16)

In [ ]:
np.finfo(np.float32)
# finfo(resolution=1e-06, min=-3.4028235e+38, max=3.4028235e+38, dtype=float32)

finfo(resolution=1e-06, min=-3.4028235e+38, max=3.4028235e+38, dtype=float32)

In [ ]:
np.finfo(np.float64)
# finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [ ]:
np.finfo(np.float128)
# finfo(resolution=1e-18, min=-1.189731495357231765e+4932, max=1.189731495357231765e+4932, dtype=float128)

finfo(resolution=1e-18, min=-1.189731495357231765e+4932, max=1.189731495357231765e+4932, dtype=float128)

In [ ]:
print(np.float16(4.12))
# 4.12
print(np.float16(4.13))
# 4.13
print(np.float16(4.123))
# 4.12
print(np.float16(4.124))
# 4.125
print(np.float16(4.125))
# 4.125

4.12
4.13
4.12
4.125
4.125


In [ ]:
print(np.sctypeDict)
print(len(np.sctypeDict))
# 158, но может быть 135 или 139

{'?': <class 'numpy.bool_'>, 0: <class 'numpy.bool_'>, 'byte': <class 'numpy.int8'>, 'b': <class 'numpy.int8'>, 1: <class 'numpy.int8'>, 'ubyte': <class 'numpy.uint8'>, 'B': <class 'numpy.uint8'>, 2: <class 'numpy.uint8'>, 'short': <class 'numpy.int16'>, 'h': <class 'numpy.int16'>, 3: <class 'numpy.int16'>, 'ushort': <class 'numpy.uint16'>, 'H': <class 'numpy.uint16'>, 4: <class 'numpy.uint16'>, 'i': <class 'numpy.int32'>, 5: <class 'numpy.int32'>, 'uint': <class 'numpy.uint64'>, 'I': <class 'numpy.uint32'>, 6: <class 'numpy.uint32'>, 'intp': <class 'numpy.int64'>, 'p': <class 'numpy.int64'>, 7: <class 'numpy.int64'>, 'uintp': <class 'numpy.uint64'>, 'P': <class 'numpy.uint64'>, 8: <class 'numpy.uint64'>, 'long': <class 'numpy.int64'>, 'l': <class 'numpy.int64'>, 'L': <class 'numpy.uint64'>, 'longlong': <class 'numpy.longlong'>, 'q': <class 'numpy.longlong'>, 9: <class 'numpy.longlong'>, 'ulonglong': <class 'numpy.ulonglong'>, 'Q': <class 'numpy.ulonglong'>, 10: <class 'numpy.ulonglong

In [ ]:
print(*sorted(map(str, set(np.sctypeDict.values()))), sep='\n')

<class 'numpy.bool_'>
<class 'numpy.bytes_'>
<class 'numpy.complex128'>
<class 'numpy.complex256'>
<class 'numpy.complex64'>
<class 'numpy.datetime64'>
<class 'numpy.float128'>
<class 'numpy.float16'>
<class 'numpy.float32'>
<class 'numpy.float64'>
<class 'numpy.int16'>
<class 'numpy.int32'>
<class 'numpy.int64'>
<class 'numpy.int8'>
<class 'numpy.longlong'>
<class 'numpy.object_'>
<class 'numpy.str_'>
<class 'numpy.timedelta64'>
<class 'numpy.uint16'>
<class 'numpy.uint32'>
<class 'numpy.uint64'>
<class 'numpy.uint8'>
<class 'numpy.ulonglong'>
<class 'numpy.void'>


In [ ]:
a = True
print(type(a))
# <class 'bool'>
a = np.bool(a)
print(type(a))
# <class 'bool'>
a = np.bool_(a)
print(type(a))
# <class 'numpy.bool_'>
 
# Значения равны
print(np.bool(True) == np.bool_(True))
# True
# А типы — нет:
print(type(np.bool(True)) == type(np.bool_(True)))
# False

<class 'bool'>
<class 'bool'>
<class 'numpy.bool_'>
True
False


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if sys.path[0] == '':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: Depr

In [ ]:
a = "Hello world!"
print(type(a))
# <class 'str'>
a = np.str(a)
print(type(a))
# <class 'str'>
a = np.str_(a)
print(type(a))
# <class 'numpy.str_'>

<class 'str'>
<class 'str'>
<class 'numpy.str_'>


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  after removing the cwd from sys.path.


In [ ]:
b = np.uint8(-456)
print(b)

56




---

# 6. Модуль NumPy. Массивы

In [ ]:
import numpy as np
arr = np.array([1,5,2,9,10])
arr
# array([ 1,  5,  2,  9, 10])

array([ 1,  5,  2,  9, 10])

In [ ]:
print(type(arr))
# <class 'numpy.ndarray'>

<class 'numpy.ndarray'>


In [ ]:
# Перечислить список из списков можно
# было и в одну строку, но на нескольких
# строках получается нагляднее
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ])
nd_arr
# array([[12, 45, 78],
#        [34, 56, 13],
#        [12, 98, 76]])

array([[12, 45, 78],
       [34, 56, 13],
       [12, 98, 76]])

In [ ]:
arr = np.array([1,5,2,9,10])
arr.dtype
# dtype('int64')

dtype('int64')

In [ ]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
arr
# array([ 1,  5,  2,  9, 10], dtype=int8)

array([ 1,  5,  2,  9, 10], dtype=int8)

In [ ]:
arr[2] = 2000
arr
# array([  1,   5, -48,   9,  10], dtype=int8)

array([  1,   5, -48,   9,  10], dtype=int8)

In [ ]:
arr[2] = 125.5
arr
# array([  1,   5, 125,   9,  10], dtype=int8)

array([  1,   5, 125,   9,  10], dtype=int8)

In [ ]:
arr[2] = '12'
arr
# array([ 1,  5, 12,  9, 10], dtype=int8)

array([ 1,  5, 12,  9, 10], dtype=int8)

In [ ]:
arr[2] = 'test'
# ValueError: invalid literal for int() with base 10: 'test'

In [ ]:
arr = np.float128(arr)
arr
# array([ 1.,  5., 12.,  9., 10.], dtype=float128)

array([ 1.,  5., 12.,  9., 10.], dtype=float128)

In [ ]:
arr = np.array([12321, -1234, 3435, -214, 100], dtype=np.int32)
arr
# array([12321, -1234,  3435,  -214,   100], dtype=int32)

array([12321, -1234,  3435,  -214,   100], dtype=int32)

In [ ]:
arr = np.uint8(arr)
arr
# array([ 33,  46, 107,  42, 100], dtype=uint8)

array([ 33,  46, 107,  42, 100], dtype=uint8)

СВОЙСТВА NUMPY-МАССИВОВ

In [ ]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

In [ ]:
arr.ndim
# 1

1

In [ ]:
nd_arr.ndim
# 2

2

In [ ]:
arr.size
# 5

5

In [ ]:
nd_arr.size
# 9

9

In [ ]:
arr.shape
# (5,)

(5,)

In [ ]:
nd_arr.shape
# (3, 3)

(3, 3)

In [ ]:
arr.itemsize
# 1

1

In [ ]:
nd_arr.itemsize
# 2

2

ЗАПОЛНЕНИЕ НОВЫХ МАССИВОВ

In [ ]:
zeros_1d = np.zeros(5)
zeros_1d
# array([0., 0., 0., 0., 0.])

array([0., 0., 0., 0., 0.])

In [ ]:
zeros_3d = np.zeros((5,4,3), dtype=np.float32)
print(zeros_3d.shape)
# (5, 4, 3)

(5, 4, 3)


In [ ]:
np.arange(5)
# array([0, 1, 2, 3, 4])

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(2.5, 5)
# array([2.5, 3.5, 4.5])

array([2.5, 3.5, 4.5])

In [ ]:
np.arange(2.5, 5, 0.5)
# array([2.5, 3. , 3.5, 4. , 4.5])

array([2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
np.arange(2.5, 5, 0.5, dtype=np.float16)
# array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

In [ ]:
arr = np.linspace(1, 2, 10)
arr
# array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
#        1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [ ]:
arr = np.linspace(1, 2, 10, endpoint=False)
arr
# array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [ ]:
arr, step = np.linspace(1, 2, 10, endpoint=True, retstep=True)
print(step)
# 0.1111111111111111

0.1111111111111111


In [ ]:
arr, step = np.linspace(1, 2, 10, endpoint=False, retstep=True)
print(step)
# 0.1

0.1


In [ ]:
arr, step = np.linspace(-6, 21, 60, endpoint=True, retstep=True)
print(round(step, 2))

0.46


In [ ]:
arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
print(round(step, 2))

0.45


In [ ]:
# from hidden import mystery
# # Пишите здесь команды, который помогут
# # найти ответы на вопросы
# print(mystery.ndim)
# print(mystery.shape)
# print(mystery.size)
# print(mystery.dtype)
# print(mystery.itemsize)



---

# 7. Модуль NumPy. Действия с массивами

ДЕЙСТВИЯ С МАССИВАМИ

In [ ]:
import numpy as np
arr = np.arange(8)
arr
# array([0, 1, 2, 3, 4, 5, 6, 7])

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr.shape = (2, 4)
arr
# array([[0, 1, 2, 3],
#        [4, 5, 6, 7]])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4))
arr_new
# array([[0, 1, 2, 3],
#       [4, 5, 6, 7]])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4), order='F')
arr_new
# array([[0, 2, 4, 6],
#       [1, 3, 5, 7]])

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [ ]:
arr = np.arange(8)
arr.shape = (2, 4)
arr
# array([[0, 1, 2, 3],
#        [4, 5, 6, 7]])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
arr_trans = arr.transpose()
arr_trans
# array([[0, 4],
#        [1, 5],
#        [2, 6],
#        [3, 7]])

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [ ]:
arr = np.arange(3)
print(arr.shape)
# (3,)
arr_trans = arr.transpose()
print(arr_trans.shape)
# (3,)

(3,)
(3,)


ИНДЕКСЫ И СРЕЗЫ В МАССИВАХ

In [ ]:
arr = np.linspace(1, 2, 6)
arr
# array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [ ]:
print(arr[2])
# 1.4

1.4


In [ ]:
print(arr[2:4])
# [1.4 1.6]

[1.4 1.6]


In [ ]:
print(arr[::-1])
# [2.  1.8 1.6 1.4 1.2 1. ]

[2.  1.8 1.6 1.4 1.2 1. ]


In [ ]:
nd_array =  np.linspace(0, 6, 12, endpoint=False).reshape(3,4)
nd_array
# array([[0. , 0.5, 1. , 1.5],
#        [2. , 2.5, 3. , 3.5],
#        [4. , 4.5, 5. , 5.5]])

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [ ]:
nd_array[1]

array([2. , 2.5, 3. , 3.5])

In [ ]:
nd_array[:, -1]

array([1.5, 3.5, 5.5])

In [ ]:
nd_array[:, -1][::-1]

array([5.5, 3.5, 1.5])

In [ ]:
nd_array[1][2]
# 3.0

3.0

In [ ]:
nd_array[1, 2]
# 3.0

3.0

In [ ]:
nd_array[:2, 2]
# array([1., 3.])

array([1., 3.])

In [ ]:
nd_array[1:, 2:4]
# array([[3. , 3.5],
#       [5. , 5.5]])

array([[3. , 3.5],
       [5. , 5.5]])

In [ ]:
nd_array[:, 2:4]
# array([[1. , 1.5],
#       [3. , 3.5],
#       [5. , 5.5]])

array([[1. , 1.5],
       [3. , 3.5],
       [5. , 5.5]])

In [ ]:
nd_array[:2]
# array([[0. , 0.5, 1. , 1.5],
#       [2. , 2.5, 3. , 3.5]])

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5]])

In [ ]:
# try:
#     from Root.src.hidden import mystery
# except ImportError:
#     from hidden import mystery
    
# # В переменную elem_5_3 сохраните элемент из 5 строки и 3 столбца:
# elem_5_3 = mystery[4, 2]

# # В переменную last сохраните элемент из последней строки последнего столбца
# last = mystery[-1, -1]

# # В переменную line_4 сохраните строку 4
# line_4 = mystery[3]

# # В переменную col_2 сохраните предпоследний столбец
# col_2 = mystery[:, -2]

# # Из строк 2-4 (включительно) получите столбцы 3-5 (включительно)
# # Результат сохраните в переменную part
# part = mystery[1:4, 2:5]

# #  Сохраните в переменную rev последний столбец в обратном порядке
# rev = mystery[:, -1][::-1]

# # Сохраните в переменную trans транспонированный массив
# trans = mystery.transpose()



---

СОРТИРОВКА ОДНОМЕРНЫХ МАССИВОВ

In [ ]:
arr = np.array([23,12,45,12,23,4,15,3])
arr_new = np.sort(arr)
print(arr)
# [23 12 45 12 23  4 15  3]
print(arr_new)
# [ 3  4 12 12 15 23 23 45]

[23 12 45 12 23  4 15  3]
[ 3  4 12 12 15 23 23 45]


In [ ]:
arr = np.array([23,12,45,12,23,4,15,3])
print(arr.sort())
# None
print(arr)
# [ 3  4 12 12 15 23 23 45]

None
[ 3  4 12 12 15 23 23 45]


РАБОТА С ПРОПУЩЕННЫМИ ДАННЫМИ

In [ ]:
data = np.array([4, 9, -4, 3])